### ISSUE TITLE
Builds but doesn't run

### ISSUE THREAD

**Issue by lgbaldoni** [mochi-player/mochi-player#3]
As per subject, I can build mochi-player but then I see
```
QQmlApplicationEngine failed to load component
qrc:/component/MochiApplication.qml:1 module "QtQuick" version 2.7 is not installed
```
libQtQuick5 5.6.1 is installed, so I can't understand what's missing.

**Comment by u8sand** [comment]
We're certainly working with Qt5.7 and I believe some features planned for
5.8 as well. You should get the latest qt release to compile mochi-player.
(>=5.7)

On Mar 25, 2017 1:09 PM, "Luigi Baldoni" <notifications@github.com> wrote:

As per subject, I can build mochi-player but then I see

QQmlApplicationEngine failed to load component
qrc:/component/MochiApplication.qml:1 module "QtQuick" version 2.7 is
not installed

libQtQuick5 5.6.1 is installed, so I can't understand what's missing.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mochi-player/mochi-player/issues/3>, or mute the thread

**Comment by lgbaldoni** [comment]
Switched to 5.7.1, now I see this:

```
QQmlApplicationEngine failed to load component
qrc:/component/MochiApplication.qml:39 Type MochiWindow unavailable
qrc:/component/MochiWindow.qml:4 module "QtQuick.Controls" version 2.0 is not installed
```

**Comment by u8sand** [comment]
Not sure on your system but I think on Arch there is qt5-quickcontrols2
package.

**Comment by lgbaldoni** [comment]
Oh, now I get it.
Thanks, that was the problem.
